// src/compliance/generator.ts — DSA Art. 17 justification generation
import { runAiCompletion } from '../ai/index.js';
import type { ModerationResult, AiOptions } from '../ai/types.js';
import { buildJustificationPrompt, buildJustificationSchema } from './prompt.js';
import type {
  ComplianceJustification,
  ComplianceAction,
  PolicyBasis,
  GenerateJustificationOptions,
} from './types.js';

function normalizePolicy(basis: PolicyBasis | string): PolicyBasis {
  if (typeof basis === 'string') {
    return { name: basis };
  }
  return basis;
}

function detectLanguage(text: string, hint?: string): string {
  if (hint) return hint;
  const germanWords = /\b(der|die|das|und|ist|zu|von|ein|in|für|mit|nicht|auch|sich)\b/gi;
  const germanMatch = (text.match(germanWords) || []).length;
  return germanMatch / (text.split(/\s+/).length || 1) > 0.15 ? 'de' : 'en';
}

function buildDefaultReason(
  action: ComplianceAction,
  language: string,
): string {
  const translations = {
    en: {
      CONTENT_REMOVED: 'Your content was removed for violating community standards.',
      CONTENT_DEMOTION: 'Your content visibility was restricted.',
      ACCOUNT_SUSPENSION: 'Your account has been suspended.',
      ACCOUNT_TERMINATION: 'Your account has been terminated.',
      FEATURE_RESTRICTION: 'Some features have been restricted on your account.',
    },
    de: {
      CONTENT_REMOVED: 'Ihr Inhalt wurde entfernt, da er gegen die Gemeinschaftsstandards verstößt.',
      CONTENT_DEMOTION: 'Die Sichtbarkeit Ihres Inhalts wurde eingeschränkt.',
      ACCOUNT_SUSPENSION: 'Ihr Konto wurde gesperrt.',
      ACCOUNT_TERMINATION: 'Ihr Konto wurde beendet.',
      FEATURE_RESTRICTION: 'Einige Funktionen auf Ihrem Konto wurden eingeschränkt.',
    },
  } as const satisfies Record<string, Record<ComplianceAction, string>>;

  return translations[language as keyof typeof translations]?.[action] ?? translations.en[action];
}


/**
 * Generate a DSA Art. 17 compliant justification for a moderation action.
 *
 * If AI is enabled, the reason and facts summary will be generated by the model
 * from the pre-determined facts. If disabled or fails, falls back to templates.
 * Never throws — a failed KI should not prevent a legal notification.
 */
export async function generateJustification(
  text: string,
  result: ModerationResult,
  options: GenerateJustificationOptions = {},
): Promise<ComplianceJustification> {
  const language = options.language || detectLanguage(text);
  const action = options.action || 'CONTENT_REMOVED';
  const policyBases = (options.policyBases || ['Community Guidelines']).map(normalizePolicy);

  let reason = buildDefaultReason(action, language);

  // Try to enhance with AI if enabled
  if (options.ai?.enabled !== false) {
    const aiOptions: AiOptions = {
      enabled: true,
      provider: (options.ai?.provider as any) || 'anthropic',
      apiKey: options.ai?.apiKey,
      model: options.ai?.model,
      effort: 'low',
      maxTokens: 512,
      onError: 'return',
    };

    const response = await runAiCompletion(
      {
        system: buildJustificationPrompt({
          action,
          categories: result.ai.categories,
          language,
          extraInstructions: options.ai?.extraInstructions,
        }),
        text: `
Action: ${action}
Categories: ${result.ai.categories.join(', ') || '(none)'}
Quote: "${result.ai.quote}"
Confidence: ${Math.round(result.ai.confidence * 100)}%

Generate reason and factsSummary as JSON.`,
        schema: buildJustificationSchema(),
      },
      aiOptions,
    );

    if (response) {
      try {
        const parsed = JSON.parse(response.json);
        if (parsed.reason && typeof parsed.reason === 'string') {
          reason = parsed.reason;
        }
      } catch {
        // Parse error — keep defaults, don't throw
      }
    }
  }

  const timestamp = new Date().toISOString();

  return {
    action,
    reason,
    policyBases,
    facts: {
      quote:
        result.ai.quote ||
        result.segments
          .filter((s) => s.isProfane)
          .map((s) => s.text)
          .join(', ') ||
        '[content]',
      categories: result.ai.categories,
      confidence: result.ai.confidence,
      automatedDetection: result.ai.status === 'ok' || result.matchedList,
      humanReview: false,
    },
    timestamp,
    duration: options.duration || 'permanent',
    language,
    appealUrl: options.appealUrl,
    additionalNotes: options.additionalNotes,
  };
}

export function exportJustification(justification: ComplianceJustification): string {
  return JSON.stringify(justification, null, 2);
}

export function formatJustificationAsText(justification: ComplianceJustification): string {
  const translations = {
    en: {
      action: 'Action taken:',
      reason: 'Reason:',
      policies: 'Policy bases:',
      categories: 'Categories:',
      confidence: 'Confidence:',
      automated: 'Automated detection:',
      humanReview: 'Human review:',
      timestamp: 'Date:',
      duration: 'Duration:',
      appeal: 'To appeal:',
      yes: 'Yes',
      no: 'No',
    },
    de: {
      action: 'Getroffene Maßnahme:',
      reason: 'Grund:',
      policies: 'Grundlagen:',
      categories: 'Kategorien:',
      confidence: 'Sicherheit:',
      automated: 'Automatische Erkennung:',
      humanReview: 'Menschliche Überprüfung:',
      timestamp: 'Datum:',
      duration: 'Dauer:',
      appeal: 'Um zu protestieren:',
      yes: 'Ja',
      no: 'Nein',
    },
  } as const satisfies Record<string, Record<string, string>>;

  const t = translations[justification.language as keyof typeof translations] ?? translations.en;

  const lines: string[] = [
    `${t.action} ${justification.action}`,
    `${t.reason} ${justification.reason}`,
    `${t.policies} ${justification.policyBases.map((p) => `${p.name}${p.section ? ' ' + p.section : ''}`).join(', ')}`,
    `${t.categories} ${justification.facts.categories.length > 0 ? justification.facts.categories.join(', ') : '(none)'}`,
    `${t.confidence} ${Math.round(justification.facts.confidence * 100)}%`,
    `${t.automated} ${justification.facts.automatedDetection ? t.yes : t.no}`,
    `${t.humanReview} ${justification.facts.humanReview ? t.yes : t.no}`,
    `${t.timestamp} ${new Date(justification.timestamp).toLocaleString(justification.language)}`,
    `${t.duration} ${justification.duration}`,
  ];

  if (justification.appealUrl) {
    lines.push(`${t.appeal} ${justification.appealUrl}`);
  }

  if (justification.additionalNotes) {
    lines.push(`\n${justification.additionalNotes}`);
  }

  return lines.join('\n');
}
