// src/compliance/generator.ts — DSA Art. 17 justification generation
import { runAiCompletion } from '../ai/index.js';
import type { ModerationResult, AiOptions } from '../ai/types.js';
import { buildJustificationPrompt, buildJustificationSchema } from './prompt.js';
import type {
  ComplianceJustification,
  ComplianceAction,
  PolicyBasis,
  GenerateJustificationOptions,
} from './types.js';

/**
 * Stands in for `facts.quote` when neither the model nor the word lists could
 * point at anything — a decision taken on something this library never saw.
 * The field stays populated so the record has no empty holes in it.
 */
const NO_EXCERPT = '[content]';

function normalizePolicy(basis: PolicyBasis | string): PolicyBasis {
  if (typeof basis === 'string') {
    return { name: basis };
  }
  return basis;
}

function detectLanguage(text: string, hint?: string): string {
  if (hint) return hint;
  const germanWords = /\b(der|die|das|und|ist|zu|von|ein|in|für|mit|nicht|auch|sich)\b/gi;
  const germanMatch = (text.match(germanWords) || []).length;
  return germanMatch / (text.split(/\s+/).length || 1) > 0.15 ? 'de' : 'en';
}

function buildDefaultReason(
  action: ComplianceAction,
  language: string,
): string {
  const translations = {
    en: {
      CONTENT_REMOVED: 'Your content was removed for violating community standards.',
      CONTENT_DEMOTION: 'Your content visibility was restricted.',
      ACCOUNT_SUSPENSION: 'Your account has been suspended.',
      ACCOUNT_TERMINATION: 'Your account has been terminated.',
      FEATURE_RESTRICTION: 'Some features have been restricted on your account.',
    },
    de: {
      CONTENT_REMOVED: 'Ihr Inhalt wurde entfernt, da er gegen die Gemeinschaftsstandards verstößt.',
      CONTENT_DEMOTION: 'Die Sichtbarkeit Ihres Inhalts wurde eingeschränkt.',
      ACCOUNT_SUSPENSION: 'Ihr Konto wurde gesperrt.',
      ACCOUNT_TERMINATION: 'Ihr Konto wurde beendet.',
      FEATURE_RESTRICTION: 'Einige Funktionen auf Ihrem Konto wurden eingeschränkt.',
    },
  } as const satisfies Record<string, Record<ComplianceAction, string>>;

  return translations[language as keyof typeof translations]?.[action] ?? translations.en[action];
}


/**
 * Generate a DSA Art. 17 compliant justification for a moderation action.
 *
 * If AI is enabled, the reason and facts summary will be generated by the model
 * from the pre-determined facts. If disabled or fails, falls back to templates.
 * Never throws — a failed KI should not prevent a legal notification.
 */
export async function generateJustification(
  text: string,
  result: ModerationResult,
  options: GenerateJustificationOptions = {},
): Promise<ComplianceJustification> {
  const language = options.language || detectLanguage(text);
  const action = options.action || 'CONTENT_REMOVED';
  const policyBases = (options.policyBases || ['Community Guidelines']).map(normalizePolicy);

  // The template wording is the floor, not the fallback of last resort: it is a
  // complete justification on its own, and it is what stays if the model is
  // slow, refuses, or was never configured.
  let reason = buildDefaultReason(action, language);

  // No `ai` option at all means no model is contacted — same rule as
  // `moderateText`. The network call is opted into, never inherited.
  const ai = options.ai;
  if (ai && ai.enabled !== false) {
    const aiOptions: AiOptions = {
      effort: 'low',
      maxTokens: 512,
      onError: 'return',
      ...(ai.provider !== undefined ? { provider: ai.provider } : {}),
      ...(ai.apiKey !== undefined ? { apiKey: ai.apiKey } : {}),
      ...(ai.model !== undefined ? { model: ai.model } : {}),
      ...(ai.complete !== undefined ? { complete: ai.complete } : {}),
    };

    const response = await runAiCompletion(
      {
        system: buildJustificationPrompt({
          action,
          categories: result.ai.categories,
          language,
          ...(ai.extraInstructions !== undefined
            ? { extraInstructions: ai.extraInstructions }
            : {}),
        }),
        // The facts, handed over as data. The model rewrites them; it never
        // gets to decide what they are.
        text: [
          `Action: ${action}`,
          `Categories: ${result.ai.categories.join(', ') || '(none)'}`,
          `Policy bases: ${policyBases
            .map((p) => `${p.name}${p.section ? ' ' + p.section : ''}`)
            .join(', ')}`,
          `Quote: ${JSON.stringify(result.ai.quote)}`,
          `Confidence: ${Math.round(result.ai.confidence * 100)}%`,
          `Duration: ${options.duration || 'permanent'}`,
        ].join('\n'),
        schema: buildJustificationSchema(),
      },
      aiOptions,
    );

    if (response) {
      try {
        const parsed: unknown = JSON.parse(response.json);
        const value = (parsed ?? {}) as Record<string, unknown>;
        if (typeof value['reason'] === 'string' && value['reason'].trim() !== '') {
          reason = value['reason'];
        }
      } catch {
        // Unparseable wording is not a reason to withhold the notification.
      }
    }
  }

  const timestamp = new Date().toISOString();

  return {
    action,
    reason,
    policyBases,
    facts: {
      // The model's own excerpt when there is one, otherwise the words the
      // lists actually matched — whichever it was, it is what the decision
      // rests on and the notice has to be able to name it.
      quote:
        result.ai.quote ||
        result.segments
          .filter((s) => s.isProfane)
          .map((s) => s.text)
          .join(', ') ||
        NO_EXCERPT,
      categories: result.ai.categories,
      confidence: result.ai.confidence,
      automatedDetection: result.ai.status === 'ok' || result.matchedList,
      humanReview: false,
    },
    timestamp,
    duration: options.duration || 'permanent',
    language,
    appealUrl: options.appealUrl,
    additionalNotes: options.additionalNotes,
  };
}

export function exportJustification(justification: ComplianceJustification): string {
  return JSON.stringify(justification, null, 2);
}

export function formatJustificationAsText(justification: ComplianceJustification): string {
  const translations = {
    en: {
      action: 'Action taken:',
      reason: 'Reason:',
      policies: 'Policy bases:',
      categories: 'Categories:',
      confidence: 'Confidence:',
      automated: 'Automated detection:',
      humanReview: 'Human review:',
      facts: 'Facts:',
      timestamp: 'Date:',
      duration: 'Duration:',
      appeal: 'To appeal:',
      yes: 'Yes',
      no: 'No',
    },
    de: {
      action: 'Getroffene Maßnahme:',
      reason: 'Grund:',
      policies: 'Grundlagen:',
      categories: 'Kategorien:',
      confidence: 'Sicherheit:',
      automated: 'Automatische Erkennung:',
      humanReview: 'Menschliche Überprüfung:',
      facts: 'Tatsachen:',
      timestamp: 'Datum:',
      duration: 'Dauer:',
      appeal: 'Um zu protestieren:',
      yes: 'Ja',
      no: 'Nein',
    },
  } as const satisfies Record<string, Record<string, string>>;

  const t = translations[justification.language as keyof typeof translations] ?? translations.en;
  const facts = justification.facts;

  const lines: string[] = [
    `${t.action} ${justification.action}`,
    `${t.reason} ${justification.reason}`,
  ];

  // Art. 17 wants the facts the decision rests on, and the excerpt *is* the
  // fact. A notice that says "you broke the rules" without saying which words
  // is exactly the notice the article was written against.
  if (facts.quote && facts.quote !== NO_EXCERPT) {
    lines.push(`${t.facts} ${JSON.stringify(facts.quote)}`);
  }

  lines.push(
    `${t.policies} ${justification.policyBases
      .map((p) => `${p.name}${p.section ? ' ' + p.section : ''}`)
      .join(', ')}`,
  );

  // Categories and confidence come from a model. When none was asked, printing
  // "(none)" and "0%" reads as an uncertain decision rather than an unasked
  // question — so those lines are simply absent instead.
  if (facts.categories.length > 0) {
    lines.push(`${t.categories} ${facts.categories.join(', ')}`);
  }
  if (facts.confidence > 0) {
    lines.push(`${t.confidence} ${Math.round(facts.confidence * 100)}%`);
  }

  lines.push(
    `${t.automated} ${facts.automatedDetection ? t.yes : t.no}`,
    `${t.humanReview} ${facts.humanReview ? t.yes : t.no}`,
    `${t.timestamp} ${new Date(justification.timestamp).toLocaleString(justification.language)}`,
    `${t.duration} ${justification.duration}`,
  );

  if (justification.appealUrl) {
    lines.push(`${t.appeal} ${justification.appealUrl}`);
  }

  if (justification.additionalNotes) {
    lines.push(`\n${justification.additionalNotes}`);
  }

  return lines.join('\n');
}
